author: "Victor Antonovich <v.antonovich@gmail.com>"
category: "admin"
summary: "Custom Ad-Hoc commands"
home: "https://github.com/3cky/ejabberd-contrib/tree/master/"
url: "git@github.com:3cky/ejabberd-contrib.git"
