version: '3.7'

services:

  prometheus:
    image: docker.io/prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: docker.io/grafana/grafana-enterprise
    container_name: grafana
    ports:
      - "3000:3000"
